PROG = projet

SRC = main.c gameInit.c playerHandler.c printingScreen.c basicFonction.c

all: $(PROG) 
	./$(PROG)

#Compilation du programme
$(PROG): $(SRC) include.h player.h gameInit.h
	gcc -Wall -o $(PROG) $(SRC)

#Nettoyage
clean:
	rm -f $(PROG)